sudo: false

language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"

install:
  - node --version
  - npm --version
  - git --version
  - svn --version | head -n 1
  - npm install

os:
  - osx
  - linux

matrix:
  allow_failures:
    - os: osx
    - env: "NODE_VERSION=0.11"

script:
  - npm test
